---
- hosts: all
  pre_tasks:
    - name: generate SSH key"
      user:
        name: "{{ansible_user}}"
        generate_ssh_key: yes
    - name: slurp file
      slurp:
        src: /root/.ssh/id_rsa.pub
      register: root_pub_key
  roles:
    - dokku_bot.ansible_dokku
    # - geerlingguy.swap
  vars:
    # If you are running dokku on a small VPS, you'll most likely
    # need some swap to ensure you don't run out of RAM during deploys
    # swap_file_size_mb: '2048'
    dokku_users:
      - name: Add ssh key
        username: caillou
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
      - name: Add ssh key
        username: root
        ssh_key: "{{ root_pub_key['content'] | b64decode }}"
    dokku_plugins:
    #   - name: clone
    #     url: https://github.com/crisward/dokku-clone.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
    dokku_hostname: 'app.caillou.ch'
    apps:
      - name: dokku
        repo: https://github.com/caillou/caillou.ch.git
      - name: hello-world
        repo: https://github.com/caillou/hello-world.html.git

  tasks:
    - name: create app
      dokku_app:
        app: "{{ item.name }}"
        state: present
      loop: "{{ apps }}"

    - name: environment configuration
      dokku_config:
        app: "{{ item.name }}"
        config:
          DOKKU_LETSENCRYPT_EMAIL: pierre.spring@caillou.ch
          PORT: "5000"
      loop: "{{ apps }}"

    - name: clone and build once
      shell: "dokku ps:inspect {{ item.name }} || (dokku git:sync {{ item.name }} {{ item.repo }} main --build && cd /home/dokku/{{item.name}} && git config --add core.bare true)"
      loop: "{{ apps }}"

    - name: Enable the letsencrypt plugin
      dokku_letsencrypt:
        app: "{{ item.name }}"
        state: present
      loop: "{{ apps }}"
