---
- hosts: all
  roles:
    - dokku_bot.ansible_dokku
    # - geerlingguy.swap
  vars:
    # If you are running dokku on a small VPS, you'll most likely
    # need some swap to ensure you don't run out of RAM during deploys
    # swap_file_size_mb: '2048'
    dokku_users:
      - name: Add ssh key
        username: caillou
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    dokku_plugins:
    #   - name: clone
    #     url: https://github.com/crisward/dokku-clone.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
    dokku_hostname: 'caillou.ch'
  tasks:
    - name: create app
      dokku_app:
        app: &appname dokku
        state: present
    - name: environment configuration
      dokku_config:
        app: *appname
        config:
          DOKKU_LETSENCRYPT_EMAIL: pierre.spring@caillou.ch
          PORT: "5000"
    # - name: Add host with custom SSH port
    #   known_hosts:
    #     name: '140.82.121.3' # github.com
    #     key: '140.82.121.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    #     path: /home/dokku/.ssh/known_hosts
    #     state: present
    - name: clone and build once
      shell: dokku ps:inspect dokku || dokku git:sync dokku https://github.com/caillou/caillou.ch.git main --build
    - name: Enable the letsencrypt plugin
      dokku_letsencrypt:
        app: *appname
        state: present
